"""initial_schema

Revision ID: 44e368d8bfce
Revises: 
Create Date: 2026-04-04 11:49:23.036333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e368d8bfce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_passwords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('salt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('admin', sa.Text(), nullable=False),
    sa.Column('trader', sa.Text(), nullable=False),
    sa.Column('client', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('scope', sa.Text(), server_default=sa.text("'full'"), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_used', sa.Text(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('user_identifier', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('success', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('column_key', sa.Text(), nullable=False),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'row_index', 'column_key', name='uq_cell_notes')
    )
    op.create_table('clients_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('deals', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('positions', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('account', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('evaluations', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('statistics', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('dropdown_options', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('identity', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('last_updated', sa.Text(), nullable=False),
    sa.Column('hedge_accounts', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('prop_accounts', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('vps_accounts', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('payment_info', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('payment_address', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('daily_checklists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('user_identifier', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('checklist_type', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.Column('items', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('submitted_at', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'user_identifier', 'checklist_type', 'client_id', name='uq_daily_checklists')
    )
    op.create_index('idx_checklist_client', 'daily_checklists', ['date', 'client_id'], unique=False)
    op.create_index('idx_checklist_date', 'daily_checklists', ['date', 'user_identifier'], unique=False)
    op.create_table('daily_watermarks',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('net_profit_complete', sa.Float(), server_default=sa.text('0.0'), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'auto'"), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('client_id', 'date')
    )
    op.create_table('data_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=True),
    sa.Column('changed_by_type', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('change_source', sa.Text(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('deals', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('positions', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('account', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('evaluations', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('statistics', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('dropdown_options', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('identity', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'version', name='uq_data_history_client_version')
    )
    op.create_index('idx_data_history_client', 'data_history', ['client_id', 'version'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_signature', sa.Text(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('phase_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('reset_id', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_client', sa.Text(), nullable=False),
    sa.Column('linked_client', sa.Text(), nullable=False),
    sa.Column('linked_by', sa.Text(), server_default=sa.text("'super_admin'"), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_client', 'linked_client', name='uq_kyc_links')
    )
    op.create_index('idx_kyc_linked', 'kyc_links', ['linked_client'], unique=False)
    op.create_index('idx_kyc_primary', 'kyc_links', ['primary_client'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('attempt_time', sa.Text(), nullable=False),
    sa.Column('success', sa.SmallInteger(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phase_name', sa.Text(), nullable=False),
    sa.Column('phase_code', sa.Text(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('ruleset', sa.Text(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('next_phase_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_code')
    )
    op.create_table('quality_scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_date', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('trader', sa.Text(), nullable=True),
    sa.Column('admin', sa.Text(), nullable=True),
    sa.Column('total_issues', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('issues', sa.Text(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('health_score', sa.Float(), server_default=sa.text('100.0'), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_scan_date', 'quality_scan_results', ['scan_date', 'client_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_token', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('user_identifier', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.Text(), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('salt', sa.Text(), nullable=False),
    sa.Column('user_type', sa.Text(), nullable=False),
    sa.Column('parent_admin', sa.Text(), nullable=True),
    sa.Column('parent_trader', sa.Text(), nullable=True),
    sa.Column('is_active', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
    sa.Column('must_change_password', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
    sa.Column('last_login', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'user_type', name='uq_user_credentials_username_type')
    )
    op.create_table('waterlog_periods',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('from_date', sa.Text(), nullable=False),
    sa.Column('to_date', sa.Text(), nullable=False),
    sa.Column('period_low', sa.Float(), nullable=True),
    sa.Column('period_high', sa.Float(), nullable=True),
    sa.Column('split_pct', sa.Integer(), server_default=sa.text('50'), nullable=True),
    sa.PrimaryKeyConstraint('client_id', 'from_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waterlog_periods')
    op.drop_table('user_credentials')
    op.drop_table('system_settings')
    op.drop_table('sessions')
    op.drop_index('idx_quality_scan_date', table_name='quality_scan_results')
    op.drop_table('quality_scan_results')
    op.drop_table('phase_definitions')
    op.drop_table('login_attempts')
    op.drop_index('idx_kyc_primary', table_name='kyc_links')
    op.drop_index('idx_kyc_linked', table_name='kyc_links')
    op.drop_table('kyc_links')
    op.drop_table('evaluations')
    op.drop_index('idx_data_history_client', table_name='data_history')
    op.drop_table('data_history')
    op.drop_table('daily_watermarks')
    op.drop_index('idx_checklist_date', table_name='daily_checklists')
    op.drop_index('idx_checklist_client', table_name='daily_checklists')
    op.drop_table('daily_checklists')
    op.drop_table('clients_data')
    op.drop_table('cell_notes')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    op.drop_table('admin_passwords')
    # ### end Alembic commands ###
